dist: xenial
language: python
python:
    - "3.7"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get -yq install apt-transport-https tor curl

install:
    - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.64.1/hugo_extended_0.64.1_Linux-64bit.deb
    - sudo dpkg -i hugo_extended_0.64.1_Linux-64bit.deb

script:
    - hugo

deploy:
    provider: pages
    skip_cleanup: true
    github-token: $GITHUB_PAT
    keep-history: true
    local-dir: public
    on:
        branch: master